---
# Source: grove-charts/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grove-operator
  labels:
    chart: "grove-charts-v0.0.0-g0f07586"
    release: "grove"
    app.kubernetes.io/component: operator-serviceaccount
    app.kubernetes.io/name: grove-operator-service-account
    app.kubernetes.io/part-of: grove
automountServiceAccountToken: false
---
# Source: grove-charts/templates/webhook-server-cert-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: grove-webhook-server-cert
  namespace: grove-system
  labels:
    chart: "grove-charts-v0.0.0-g0f07586"
    release: "grove"
    app.kubernetes.io/component: operator-webhook-server-secret
    app.kubernetes.io/name: grove-webhook-server-secret
    app.kubernetes.io/part-of: grove
type: kubernetes.io/tls
data:
  tls.crt: ""
  tls.key: ""
---
# Source: grove-charts/templates/configmap-operator.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: grove-operator-cm-43dfd1c0
  namespace: grove-system
  labels:
    chart: "grove-charts-v0.0.0-g0f07586"
    release: "grove"
    app.kubernetes.io/component: operator-configmap
    app.kubernetes.io/name: grove-operator
    app.kubernetes.io/part-of: grove
immutable: true
data:
  config.yaml: |
    apiVersion: operator.config.grove.io/v1alpha1
    kind: OperatorConfiguration
    runtimeClientConnection:
      qps: 100
      burst: 150
    leaderElection:
      enabled: true
      leaseDuration: 15s
      renewDeadline: 10s
      retryPeriod: 2s
      resourceLock: leases
      resourceName: grove-operator-leader-election
      resourceNamespace: grove-system
    server:
      webhooks:
        port: 9443
      healthProbes:
        port: 9444
      metrics:
        port: 9445
    controllers:
      podCliqueSet:
        concurrentSyncs: 3
      podClique:
        concurrentSyncs: 3
    debugging:
      enableProfiling: false
    logLevel: info
    logFormat: json
    clusterTopology:
      enabled: false
      name: grove-topology
---
# Source: grove-charts/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grove:system:grove-operator
  labels:
    chart: "grove-charts-v0.0.0-g0f07586"
    release: "grove"
    app.kubernetes.io/component: operator-clusterrole
    app.kubernetes.io/name: grove-operator
    app.kubernetes.io/part-of: grove
rules:
- apiGroups:
  - scheduler.grove.io
  resources:
  - podgangs
  verbs:
  - create
  - get
  - list
  - watch
  - delete
  - deletecollection
  - patch
  - update
- apiGroups:
  - grove.io
  resources:
  - podcliquesets
  - podcliquesets/status
  - podcliques
  - podcliques/status
  - podcliquescalinggroups
  - podcliquescalinggroups/status
  verbs:
  - create
  - get
  - list
  - watch
  - delete
  - deletecollection
  - patch
  - update
- apiGroups:
  - grove.io
  resources:
  - clustertopologies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  - pods/status
  - serviceaccounts
  - services
  - secrets
  verbs:
  - create
  - get
  - list
  - watch
  - delete
  - deletecollection
  - patch
  - update
- apiGroups:
    - ""
  resources:
    - secrets
  verbs:
    - create
    - get
    - list
    - patch
    - delete
    - watch
    - update
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  - mutatingwebhookconfigurations
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - get
  - list
  - watch
  - patch
- apiGroups:
    - ""
  resources:
    - secrets
  verbs:
    - create
    - get
    - list
    - patch
    - delete
    - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  verbs:
  - create
  - get
  - list
  - watch
  - delete
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - create
  - get
  - list
  - delete
  - deletecollection
  - patch
  - update
  - watch
---
# Source: grove-charts/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grove:system:grove-operator
  labels:
    chart: "grove-charts-v0.0.0-g0f07586"
    release: "grove"
    app.kubernetes.io/component: operator-clusterrolebinding
    app.kubernetes.io/name: grove-operator
    app.kubernetes.io/part-of: grove
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: grove:system:grove-operator
subjects:
- kind: ServiceAccount
  name: grove-operator
  namespace: grove-system
---
# Source: grove-charts/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: grove-operator
  labels:
    chart: "grove-charts-v0.0.0-g0f07586"
    release: "grove"
    app.kubernetes.io/component: operator-serviceaccount
    app.kubernetes.io/name: grove-operator-service-account
    app.kubernetes.io/part-of: grove
spec:
  type: ClusterIP
  selector:
    
    app.kubernetes.io/component: operator-deployment
    app.kubernetes.io/name: grove-operator
    app.kubernetes.io/part-of: grove
  ports:
    - name: metrics
      protocol: TCP
      port: 9445
      targetPort: 9445
    - name: webhooks
      protocol: TCP
      port: 9443
      targetPort: 9443
---
# Source: grove-charts/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grove-operator
  namespace: grove-system
  labels:
    chart: "grove-charts-v0.0.0-g0f07586"
    release: "grove"
    app.kubernetes.io/component: operator-deployment
    app.kubernetes.io/name: grove-operator
    app.kubernetes.io/part-of: grove
spec:
  replicas: 1
  selector:
    matchLabels:
      
      app.kubernetes.io/component: operator-deployment
      app.kubernetes.io/name: grove-operator
      app.kubernetes.io/part-of: grove
  template:
    metadata:
      labels:
        chart: "grove-charts-v0.0.0-g0f07586"
        release: "grove"
        app.kubernetes.io/component: operator-deployment
        app.kubernetes.io/name: grove-operator
        app.kubernetes.io/part-of: grove
    spec:
      serviceAccountName: grove-operator
      automountServiceAccountToken: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: grove-operator
          image: ccr.ccs.tencentyun.com/acejilam/ib-95zbwqlysf:8d92445f7b4a1c8d0b906f7ecea736ab-v0.0.0-g0f07586
          # image: ghcr.io/ai-dynamo/grove/grove-operator:v0.0.0-g0f07586
          imagePullPolicy: IfNotPresent
          args:
            - --config=/etc/grove-operator/config/config.yaml
          resources:
            limits:
              memory: 1Gi
            requests:
              cpu: 50m
              ephemeral-storage: 128Mi
              memory: 128Mi
          volumeMounts:
            - name: operator-config
              mountPath: /etc/grove-operator/config
            - name: kube-api-access-grove
              mountPath: /var/run/secrets/kubernetes.io/serviceaccount
              readOnly: true
            - name: grove-webhook-server-cert
              mountPath: /etc/grove-operator/webhook-certs
              readOnly: true
          env:
            - name: GROVE_OPERATOR_SERVICE_ACCOUNT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
            - name: GROVE_INIT_CONTAINER_IMAGE
              value: ghcr.io/ai-dynamo/grove/grove-initc
      volumes:
        - name: kube-api-access-grove
          projected:
            defaultMode: 420
            sources:
              - serviceAccountToken:
                  path: token
                  expirationSeconds: 43200 # 12 hours
              - configMap:
                  name: kube-root-ca.crt
                  items:
                  - key: ca.crt
                    path: ca.crt
              - downwardAPI:
                  items:
                    - path: namespace
                      fieldRef:
                        fieldPath: metadata.namespace
                        apiVersion: v1
        - name: operator-config
          configMap:
            name: grove-operator-cm-43dfd1c0
        - name: grove-webhook-server-cert
          secret:
            secretName: grove-webhook-server-cert
            defaultMode: 420
---
# Source: grove-charts/templates/pcs-defaulting-webhook-config.yaml
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: podcliqueset-defaulting-webhook
  labels:
    chart: "grove-charts-v0.0.0-g0f07586"
    release: "grove"
    app.kubernetes.io/component: operator-pcs-defaulting-webhook
    app.kubernetes.io/name: pcs-defaulting-webhook
    app.kubernetes.io/part-of: grove
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: grove-operator
        namespace: grove-system
        path: /webhooks/default-podcliqueset
        port: 9443
    failurePolicy: Fail
    matchPolicy: Exact
    name: pcs.defaulting.webhooks.grove.io
    namespaceSelector: { }
    rules:
      - apiGroups:
          - "grove.io"
        apiVersions:
          - "v1alpha1"
        operations:
          - CREATE
          - UPDATE
        resources:
          - podcliquesets
        scope: "Namespaced"
    sideEffects: None
    timeoutSeconds: 10
---
# Source: grove-charts/templates/clustertopology-validating-webhook-config.yaml
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: clustertopology-validating-webhook
  labels:
    chart: "grove-charts-v0.0.0-g0f07586"
    release: "grove"
    app.kubernetes.io/component: operator-clustertopology-validating-webhook
    app.kubernetes.io/name: clustertopology-validating-webhook
    app.kubernetes.io/part-of: grove
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: grove-operator
        namespace: grove-system
        path: /webhooks/validate-clustertopology
        port: 9443
    failurePolicy: Fail
    matchPolicy: Exact
    name: clustertopology.validating.webhooks.grove.io
    namespaceSelector: { }
    rules:
      - apiGroups:
          - "grove.io"
        apiVersions:
          - "v1alpha1"
        operations:
          - CREATE
          - UPDATE
        resources:
          - clustertopologies
        scope: Cluster
    sideEffects: None
    timeoutSeconds: 10
---
# Source: grove-charts/templates/pcs-validating-webhook-config.yaml
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: podcliqueset-validating-webhook
  labels:
    chart: "grove-charts-v0.0.0-g0f07586"
    release: "grove"
    app.kubernetes.io/component: operator-pcs-validating-webhook
    app.kubernetes.io/name: pcs-validating-webhook
    app.kubernetes.io/part-of: grove
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: grove-operator
        namespace: grove-system
        path: /webhooks/validate-podcliqueset
        port: 9443
    failurePolicy: Fail
    matchPolicy: Exact
    name: pcs.validating.webhooks.grove.io
    namespaceSelector: { }
    rules:
      - apiGroups:
          - "grove.io"
        apiVersions:
          - "v1alpha1"
        operations:
          - CREATE
          - UPDATE
        resources:
          - podcliquesets
        scope: "Namespaced"
    sideEffects: None
    timeoutSeconds: 10
