server_name: nats-1

port: 4222
monitor_port: 8222

; system_account: SYS
;
; accounts {
;   SYS {
;     users = [
;       { user: sys, password: syspass }
;     ]
;   }
; }

cluster {
  name: "my_cluster"
  port: 6222

  authorization {
    user: ruser
    password: T0pS3cr3t
    timeout: 2
  }

  routes = []
}
