server_name: nats-1

port: 4222

http_port: 8222

accounts {
  SYS {
    jetstream: enabled
    users = [
      { user: user, password: pass }
    ]
  }
}

jetstream {
  max_mem_store: 1GiB
  max_file_store: 1GiB
  store_dir: /data/jetstream
}